### ISSUE TITLE
The page displays an error when running this project

### ISSUE THREAD

**Issue by zhang-xing-tfs** [upstash/wikipedia-semantic-search#9]
![image](https://github.com/user-attachments/assets/1b4da0b6-6197-4e4b-8781-4e77eb238fa3)

**Comment by ytkimirti** [comment]
It's probably because you don't have a namespace in your vector index, I will add a warning instead of throwing an error, thanks!

**Comment by willson113** [comment]
Can you provide a documentation? How to call this work? How to use this work in your own python program? Thank you!
